;;; flimenu-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flimenu.el

(autoload 'flimenu-mode "flimenu" "\
Toggle the automatic flattening of imenu indexes.

This is a minor mode.  If called interactively, toggle the
`Flimenu mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `flimenu-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'flimenu-global-mode 'globalized-minor-mode t)
(defvar flimenu-global-mode nil "\
Non-nil if Flimenu-Global mode is enabled.
See the `flimenu-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `flimenu-global-mode'.")
(custom-autoload 'flimenu-global-mode "flimenu" nil)
(autoload 'flimenu-global-mode "flimenu" "\
Toggle Flimenu mode in all buffers.
With prefix ARG, enable Flimenu-Global mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Flimenu mode is enabled in all buffers where `flimenu-mode-turn-on'
would do it.

See `flimenu-mode' for more information on Flimenu mode.

(fn &optional ARG)" t)
(register-definition-prefixes "flimenu" '("flimenu-"))

;;; End of scraped data

(provide 'flimenu-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flimenu-autoloads.el ends here
