;;; rutils-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from rutils-devtools.el

 (autoload 'rutils-devtools "rutils-devtools" nil t)


;;; Generated autoloads from rutils-lib.el

(register-definition-prefixes "rutils-lib" '("rutils-"))


;;; Generated autoloads from rutils-packrat.el

 (autoload 'rutils-packrat-init "rutils-packrat" nil t)
 (autoload 'rutils-packrat-snapshot "rutils-packrat" nil t)
 (autoload 'rutils-packrat-status "rutils-packrat" nil t)
 (autoload 'rutils-packrat-restore "rutils-packrat" nil t)
 (autoload 'rutils-packrat-bundle "rutils-packrat" nil t)
 (autoload 'rutils-packrat-unbundle "rutils-packrat" nil t)
 (autoload 'rutils-packrat-clean "rutils-packrat" nil t)
 (autoload 'rutils-packrat-disable "rutils-packrat" nil t)
 (autoload 'rutils-packrat "rutils-packrat" nil t)
(register-definition-prefixes "rutils-packrat" '("rutils-packrat-"))


;;; Generated autoloads from rutils-renv.el

 (autoload 'rutils-renv-init "rutils-renv" nil t)
 (autoload 'rutils-renv-snapshot "rutils-renv" nil t)
 (autoload 'rutils-renv-status "rutils-renv" nil t)
 (autoload 'rutils-renv-restore "rutils-renv" nil t)
 (autoload 'rutils-renv-update "rutils-renv" nil t)
 (autoload 'rutils-renv-hydrate "rutils-renv" nil t)
 (autoload 'rutils-renv-dependencies "rutils-renv" nil t)
 (autoload 'rutils-renv-install "rutils-renv" nil t)
 (autoload 'rutils-renv "rutils-renv" nil t)
(register-definition-prefixes "rutils-renv" '("rutils-renv-"))

;;; End of scraped data

(provide 'rutils-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; rutils-autoloads.el ends here
